# Обов'язкові метадані проєкту
sonar.projectKey=lab11
sonar.projectName=lab11
sonar.projectVersion=1.0.0

# Опис проєкту (можна будь-який)
sonar.projectDescription=This project demonstrates a simple node js.

# Шлях до папки з кодом (крапка означає поточну папку)
sonar.sources=./

# Мова програмування та кодування
sonar.language=js
sonar.sourceEncoding=UTF-8
